[versions]
agp = "8.2.2"
kotlin = "1.9.22"
ktlint = "12.1.0"
coroutines = "1.7.3"
recyclerview = "1.2.1"
junit = "4.13.2"
compose-bom = "2024.02.00"
activity-compose = "1.8.2"
lifecycle-viewmodel-compose = "2.7.0"
navigation-compose = "2.7.7"
preference-ktx = "1.2.1"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
junit = { module = "junit:junit", version.ref = "junit" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose-ui = { module = "androidx.compose.ui:ui" }
compose-material3 = { module = "androidx.compose.material3:material3" }
compose-material-icons = { module = "androidx.compose.material:material-icons-extended" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activity-compose" }
lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigation-compose" }
preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
